export const CHANGE_MATRIX = 'CHANGE_MATRIX';

export const INCREMENT_VALUE = 'INCREMENT_VALUE';

export const FIND_SIMILAR_VALUES = 'FIND_SIMILAR_VALUES';
export const RESET_SIMILAR_VALUES = 'RESET_SIMILAR_VALUES';

export const CALCULATE_MATRIX_PERCENT = 'CALCULATE_MATRIX_PERCENT';
export const RESET_MATRIX_PERCENT = 'RESET_MATRIX_PERCENT';

export const DELETE_ROW = 'DELETE_ROW';
